apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  annotations:
    dummy-annotation: "trigger-update"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: docker-cdcp
      containers:
      - name: frontend
        image: dynamicdevops/cdcp:frontend_cdcp1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000